### ISSUE TITLE
Confirm masking procedure

### ISSUE THREAD

**Issue by emdupre** [pauljaffe/openneurofirstlevel#3]
> I'd be curious how people think one should combine masks across different runs (this is sort of minor, but see combine_run_masks in utils.py if you are curious)

Just to make sure I understand what's currently going on : In `combine_run_masks`, multiple run-level masks are combined into a single mask with `np.prod` :

https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/openneuro_firstlevel/utils.py#L97-L101

These masks are gathered in `fit_single_subject`:

https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/openneuro_firstlevel/first_level.py#L103-L116

And used in `analyze_contrasts`:

https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/openneuro_firstlevel/first_level.py#L243-L255

In general, I don't know what kinds of `space_label`'s are supported in `fit_single_subject`. But, I'm not sure why you would _need_ to use run-specific masks for data that's processed to a standard space. Could you not just use the standard space mask instead ? For subject-specific data, I'd think to use the anatomical mask. That's what I did when [running fixed-effects analyses in the past](https://github.com/courtois-neuromod/hcptrt_ffx/blob/master/hcptrt_ffx/generate_ffx.py), building from [some analyses from IBC](https://github.com/individual-brain-charting/public_analysis_code/blob/master/scripts/glm_only.py).

**Comment by pauljaffe** [comment]
Thanks! That all makes sense. Given that we decided to do no masking yesterday, I'll close this (btw, it turns out that computing the elementwise product of those masks as I was doing is completely untenable, unsurprisingly the memory burden is huge! could consider calculating the product sequentially, but moot now...)

**Comment by emdupre** [comment]
I'm not surprised it's heavy 😅 
But if you _do_ come back to masking (again for computational reasons, I'd guess), I'd really encourage using one of the e.g. template masks, rather than optimizing how you compute the product !
